from __future__ import annotations

from app.agent.agent_models import ToolSpec


TOOL_REGISTRY: dict[str, ToolSpec] = {
    "help": ToolSpec("help", "Show agent help.", "low"),
    "list_tools": ToolSpec("list_tools", "Show available agent tools.", "low"),
    "list_skills": ToolSpec("list_skills", "Show available agent skills.", "low"),
    "unknown": ToolSpec("unknown", "Show safe fallback examples for unknown input.", "low"),
    "blocked_request": ToolSpec("blocked_request", "Blocked unsafe user request.", "high", allowed_in_agent=False),
    "status": ToolSpec("status", "Show session status.", "low"),
    "clear": ToolSpec("clear", "Clear the terminal.", "low"),
    "show_devices": ToolSpec("show_devices", "List stored devices.", "low"),
    "show_device": ToolSpec("show_device", "Show one device profile.", "low"),
    "latest_report": ToolSpec("latest_report", "Show latest stored report.", "low"),
    "nmap_check": ToolSpec("nmap_check", "Check optional nmap availability.", "low"),
    "nmap_scan_local": ToolSpec("nmap_scan_local", "Run a controlled nmap scan on the local private network.", "medium", True, reason="It will run an approved nmap profile against a private local target."),
    "nmap_scan_host": ToolSpec("nmap_scan_host", "Run a controlled nmap scan on one private host.", "medium", True, reason="It will run an approved nmap profile against a private host."),
    "nmap_scan_device": ToolSpec("nmap_scan_device", "Run a controlled nmap scan on one inventory device.", "medium", True, reason="It will run an approved nmap profile against an inventory device."),
    "ask": ToolSpec("ask", "Ask DeepSeek using local context only.", "low"),
    "diagnose_network": ToolSpec("diagnose_network", "Diagnose network from stored data.", "low"),
    "diagnose_device": ToolSpec("diagnose_device", "Diagnose one known device.", "low"),
    "diagnose_management_ports": ToolSpec("diagnose_management_ports", "Show possible management/service ports.", "low"),
    "diagnose_connectivity": ToolSpec("diagnose_connectivity", "Run safe private-IP connectivity diagnosis.", "low"),
    "knowledge_list": ToolSpec("knowledge_list", "List local knowledge.", "low"),
    "knowledge_show": ToolSpec("knowledge_show", "Show a knowledge document.", "low"),
    "knowledge_search": ToolSpec("knowledge_search", "Search local knowledge.", "low"),
    "list_plans": ToolSpec("list_plans", "List change plans.", "low"),
    "show_plan": ToolSpec("show_plan", "Show a change plan.", "low"),
    "lab_checklist": ToolSpec("lab_checklist", "Show lab checklist.", "low"),
    "lab_validate_device": ToolSpec("lab_validate_device", "Validate lab device readiness from stored data.", "low"),
    "lab_validate_plan": ToolSpec("lab_validate_plan", "Validate lab plan readiness without execution.", "low"),
    "build_topology": ToolSpec("build_topology", "Build a read-only topology snapshot.", "low"),
    "show_topology": ToolSpec("show_topology", "Show latest topology snapshot.", "low"),
    "export_topology_json": ToolSpec("export_topology_json", "Export topology as JSON.", "low"),
    "export_topology_mermaid": ToolSpec("export_topology_mermaid", "Export topology as Mermaid.", "low"),
    "export_topology_file": ToolSpec("export_topology_file", "Write topology export to a local file.", "low"),
    "topology_report_file": ToolSpec("topology_report_file", "Write topology report to a local Markdown file.", "low"),
    "explain_topology": ToolSpec("explain_topology", "Explain topology evidence and confidence.", "low"),
    "topology_risk_check": ToolSpec("topology_risk_check", "Inspect topology-aware warnings for a plan.", "low"),
    "list_snapshots": ToolSpec("list_snapshots", "List config snapshots.", "low"),
    "show_snapshot": ToolSpec("show_snapshot", "Show a config snapshot.", "low"),
    "snapshot_restore_guidance": ToolSpec("snapshot_restore_guidance", "Show deterministic snapshot restore guidance.", "low"),
    "export_snapshot_file": ToolSpec("export_snapshot_file", "Write snapshot export to a local file.", "low"),
    "capture_snapshot": ToolSpec("capture_snapshot", "Capture a read-only manual config snapshot.", "medium", True, reason="It opens SSH with stored credentials and runs read-only snapshot commands."),
    "list_manual_topology": ToolSpec("list_manual_topology", "List manual topology corrections.", "low"),
    "add_manual_topology_node": ToolSpec("add_manual_topology_node", "Add a manual topology node locally.", "low"),
    "add_manual_topology_edge": ToolSpec("add_manual_topology_edge", "Add a manual topology edge locally.", "low"),
    "rebuild_topology_with_manual": ToolSpec("rebuild_topology_with_manual", "Rebuild topology with manual corrections.", "low"),
    "scan_network": ToolSpec("scan_network", "Scan detected local private network.", "medium", True, reason="It will scan your local private network."),
    "enrich_devices": ToolSpec("enrich_devices", "Run passive enrichment on stored devices.", "medium", True, reason="It may connect to discovered service ports for banners/titles."),
    "connect_collect": ToolSpec("connect_collect", "Run allowlisted read-only collection.", "medium", True, reason="It opens SSH with stored credentials and runs read-only allowlisted commands."),
    "router_connect_workflow": ToolSpec("router_connect_workflow", "Detect gateway and guide read-only router connection.", "medium", True, reason="It may scan/enrich or open read-only SSH collection after confirmation."),
    "preflight_plan_refresh": ToolSpec("preflight_plan_refresh", "Run preflight with read-only refresh.", "medium", True, reason="It may connect read-only using stored credentials."),
    "preflight_plan": ToolSpec("preflight_plan", "Run stored-data preflight.", "low"),
    "review_plan": ToolSpec("review_plan", "Mark a plan reviewed.", "medium", True, reason="It changes local plan lifecycle state."),
    "create_vlan_plan": ToolSpec("create_vlan_plan", "Create a Cisco VLAN plan.", "medium", True, reason="It creates a local configuration plan."),
    "create_cisco_description_plan": ToolSpec("create_cisco_description_plan", "Create a Cisco interface description plan.", "medium", True, reason="It creates a local configuration plan."),
    "create_cisco_access_port_plan": ToolSpec("create_cisco_access_port_plan", "Create a Cisco access-port plan.", "medium", True, reason="It creates a local configuration plan."),
    "create_mikrotik_address_plan": ToolSpec("create_mikrotik_address_plan", "Create a MikroTik address plan.", "medium", True, reason="It creates a local configuration plan."),
    "create_mikrotik_dhcp_plan": ToolSpec("create_mikrotik_dhcp_plan", "Create a MikroTik DHCP server plan.", "medium", True, reason="It creates a local configuration plan."),
    "custom_plan_goal": ToolSpec("custom_plan_goal", "Generate and optionally execute a DeepSeek custom Cisco/RouterOS plan.", "high", True, reason="It can create and execute high-impact generated network commands after confirmation."),
    "generate_plugin_tool": ToolSpec("generate_plugin_tool", "Generate a pure local plugin tool for unsupported tasks.", "medium", True, reason="It asks the LLM to write local plugin code, then validates it before approval."),
    "fetch_docs_url": ToolSpec("fetch_docs_url", "Fetch public documentation into local knowledge.", "medium", True, reason="It makes an explicit internet request."),
    "workflow_scan_and_diagnose": ToolSpec("workflow_scan_and_diagnose", "Scan, enrich, diagnose, and build topology.", "medium", True, reason="It scans your local private network and runs passive enrichment."),
    "workflow_topology_report": ToolSpec("workflow_topology_report", "Build topology and write a Markdown report.", "low"),
    "workflow_prepare_cisco_access_port": ToolSpec("workflow_prepare_cisco_access_port", "Interactively create a Cisco access-port plan only.", "medium", True, reason="It creates a local configuration plan."),
    "workflow_prepare_mikrotik_dhcp": ToolSpec("workflow_prepare_mikrotik_dhcp", "Interactively create a MikroTik DHCP plan only.", "medium", True, reason="It creates a local configuration plan."),
    "execute_plan": ToolSpec("execute_plan", "Execute a plan.", "high", False, False, True, "python main.py plan execute {plan_id}"),
    "save_plan": ToolSpec("save_plan", "Save a plan's config.", "high", False, False, True, "python main.py plan save {plan_id}"),
    "rollback_plan": ToolSpec("rollback_plan", "Rollback a plan.", "high", False, False, True, "python main.py plan rollback {plan_id}"),
    "delete_knowledge": ToolSpec("delete_knowledge", "Delete local knowledge.", "high", False, False, True, "python main.py knowledge delete {knowledge_id}"),
    "delete_credentials": ToolSpec("delete_credentials", "Delete stored credentials.", "high", False, False, True, "python main.py credentials delete <ip>"),
    "delete_manual_topology": ToolSpec("delete_manual_topology", "Delete manual topology data.", "high", False, False, True, "python main.py topology manual-node delete <id>"),
}


def get_tool_spec(tool_name: str) -> ToolSpec | None:
    return TOOL_REGISTRY.get(tool_name)
